
SCRIPT_DIR:=./scripts
BUILD_DIR:=./build

ReplicatorTest:
	$(SCRIPT_DIR)/compile -c ./ReplicatorTestbench.bsv mkTestbench 1

AdderTest:
	$(SCRIPT_DIR)/compile -c ./AdderTestbench.bsv mkTestbench 1

MultiplierTest:
	$(SCRIPT_DIR)/compile -c ./MultiplierTestbench.bsv mkTestbench 1

run:
	$(SCRIPT_DIR)/compile -r

clean:
	$(SCRIPT_DIR)/compile -clean

